/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SemanticSearch_CONSTANTS_H
#define SemanticSearch_CONSTANTS_H

#include "SemanticSearch_types.h"



class SemanticSearchConstants {
 public:
  SemanticSearchConstants();

};

extern const SemanticSearchConstants g_SemanticSearch_constants;



#endif
