/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef InternalService_H
#define InternalService_H

#include <thrift/TDispatchProcessor.h>
#include "InternalService_types.h"

namespace robosay {

class InternalServiceIf {
 public:
  virtual ~InternalServiceIf() {}
  virtual void process(std::string& _return, const std::string& sCmd) = 0;
};

class InternalServiceIfFactory {
 public:
  typedef InternalServiceIf Handler;

  virtual ~InternalServiceIfFactory() {}

  virtual InternalServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(InternalServiceIf* /* handler */) = 0;
};

class InternalServiceIfSingletonFactory : virtual public InternalServiceIfFactory {
 public:
  InternalServiceIfSingletonFactory(const boost::shared_ptr<InternalServiceIf>& iface) : iface_(iface) {}
  virtual ~InternalServiceIfSingletonFactory() {}

  virtual InternalServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(InternalServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<InternalServiceIf> iface_;
};

class InternalServiceNull : virtual public InternalServiceIf {
 public:
  virtual ~InternalServiceNull() {}
  void process(std::string& /* _return */, const std::string& /* sCmd */) {
    return;
  }
};

typedef struct _InternalService_process_args__isset {
  _InternalService_process_args__isset() : sCmd(false) {}
  bool sCmd;
} _InternalService_process_args__isset;

class InternalService_process_args {
 public:

  InternalService_process_args() : sCmd() {
  }

  virtual ~InternalService_process_args() throw() {}

  std::string sCmd;

  _InternalService_process_args__isset __isset;

  void __set_sCmd(const std::string& val) {
    sCmd = val;
  }

  bool operator == (const InternalService_process_args & rhs) const
  {
    if (!(sCmd == rhs.sCmd))
      return false;
    return true;
  }
  bool operator != (const InternalService_process_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InternalService_process_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class InternalService_process_pargs {
 public:


  virtual ~InternalService_process_pargs() throw() {}

  const std::string* sCmd;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InternalService_process_result__isset {
  _InternalService_process_result__isset() : success(false) {}
  bool success;
} _InternalService_process_result__isset;

class InternalService_process_result {
 public:

  InternalService_process_result() : success() {
  }

  virtual ~InternalService_process_result() throw() {}

  std::string success;

  _InternalService_process_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const InternalService_process_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const InternalService_process_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InternalService_process_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InternalService_process_presult__isset {
  _InternalService_process_presult__isset() : success(false) {}
  bool success;
} _InternalService_process_presult__isset;

class InternalService_process_presult {
 public:


  virtual ~InternalService_process_presult() throw() {}

  std::string* success;

  _InternalService_process_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class InternalServiceClient : virtual public InternalServiceIf {
 public:
  InternalServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  InternalServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void process(std::string& _return, const std::string& sCmd);
  void send_process(const std::string& sCmd);
  void recv_process(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class InternalServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<InternalServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (InternalServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_process(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  InternalServiceProcessor(boost::shared_ptr<InternalServiceIf> iface) :
    iface_(iface) {
    processMap_["process"] = &InternalServiceProcessor::process_process;
  }

  virtual ~InternalServiceProcessor() {}
};

class InternalServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  InternalServiceProcessorFactory(const ::boost::shared_ptr< InternalServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< InternalServiceIfFactory > handlerFactory_;
};

class InternalServiceMultiface : virtual public InternalServiceIf {
 public:
  InternalServiceMultiface(std::vector<boost::shared_ptr<InternalServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~InternalServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<InternalServiceIf> > ifaces_;
  InternalServiceMultiface() {}
  void add(boost::shared_ptr<InternalServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void process(std::string& _return, const std::string& sCmd) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->process(_return, sCmd);
    }
    ifaces_[i]->process(_return, sCmd);
    return;
  }

};

} // namespace

#endif
