/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef InternalService_CONSTANTS_H
#define InternalService_CONSTANTS_H

#include "InternalService_types.h"

namespace robosay {

class InternalServiceConstants {
 public:
  InternalServiceConstants();

};

extern const InternalServiceConstants g_InternalService_constants;

} // namespace

#endif
